version: "2.10.2"
services:
  requirements:
    image: python:3.7
    command: pip install -r requirements.txt

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"

  api-service:
    build: ./api/
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1

  producer:
    container_name: producer
    build:
      context: /producer
      dockerfile: Dockerfile
    depends_on:
      - requirements
      - redis

  consumer:
    container_name: consumer
    build:
      context: /consumer
      dockerfile: Dockerfile
    depends_on:
      - requirements
      - redis