version: "2.10.2"
services:

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 123456789
    ports:
      - 6379:6379
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4
    expose:
      - "6379"

  api-service:
    build: ./api/
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
    depends_on:
      - redis

  producer:
    container_name: producer
    build: ./producer/
    volumes:
      - ./producer/:/usr/src/producer/
    ports:
      - 5100:5100
    environment:
      PORT: 5100
    depends_on:
      - redis

  consumer:
    container_name: consumer
    build: ./consumer/
    volumes:
      - ./consumer/:/usr/src/consumer/
    ports:
      - 5200:5200
    environment:
      PORT: 5200
    depends_on:
      - redis

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16